#import <Foundation/Foundation.h>
// Public umbrella header for Caelum (SwiftPM)
// Core
#import "Core/CLMLogger.h"
#import "Core/CLMErrors.h"
#import "Core/CLMClock.h"
// REST
#import "REST/CLMRESTConfiguration.h"
#import "REST/CLMRESTRequest.h"
#import "REST/CLMRESTResponse.h"
#import "REST/CLMRateLimiter.h"
#import "REST/CLMDiscordRESTClient.h"
#import "REST/CLMMessagesPaginator.h"
#import "REST/CLMMembersPaginator.h"
// Gateway
#import "Gateway/CLMGatewayConfiguration.h"
#import "Gateway/CLMWebSocketConnection.h"
#import "Gateway/CLMDiscordGatewayClient.h"
// Models
#import "Models/CLMSnowflake.h"
// Components & Interactions
#import "Models/Components/CLMComponents.h"
#import "Models/Components/CLMButton.h"
#import "Models/Components/CLMSelectMenu.h"
#import "Models/Components/CLMSelectMenuOption.h"
#import "Models/Components/CLMActionRow.h"
#import "Models/Components/CLMTextInput.h"
#import "Models/Interactions/CLMComponentInteraction.h"
// AutoMod
#import "Models/AutoMod/CLMAutoModAction.h"
#import "Models/AutoMod/CLMAutoModTrigger.h"
#import "Models/AutoMod/CLMAutoModRule.h"
// Localization
#import "Models/Localization/CLMLocale.h"
#import "Models/Localization/CLMLocalizedString.h"
// Forum
#import "Models/Forum/CLMForumChannel.h"
#import "Models/Forum/CLMForumTag.h"
// Polls
#import "Models/Polls/CLMPoll.h"
#import "Models/Polls/CLMPollAnswer.h"
// Client
#import "Client/CLMDiscordClient.h"
#import "Client/CLMClientConfiguration.h"
// Commands (scaffolding)
#import "Commands/CLMCommand.h"
#import "Commands/CLMCommandContext.h"
#import "Commands/CLMCommandRouter.h"
#import "Commands/CLMCommandCooldownManager.h"
#import "Commands/CLMCommandPermissionChecker.h"

